return {
    getWeaponList ={
        GetHashKey("WEAPON_SNOWLAUNCHER"),
        GetHashKey("WEAPON_COMPACTLAUNCHER"),
        GetHashKey("WEAPON_MINIGUN"),
        GetHashKey("WEAPON_GRENADELAUNCHER_SMOKE"),
        GetHashKey("WEAPON_RAILGUN"),
        GetHashKey("WEAPON_FIREWORK"),
        GetHashKey("WEAPON_GRENADELAUNCHER"),
        GetHashKey("WEAPON_RPG"),
        GetHashKey("WEAPON_HOMINGLAUNCHER"),
        GetHashKey("WEAPON_RAYMINIGUN"),
        GetHashKey("WEAPON_EMPLAUNCHER"),
        GetHashKey("WEAPON_RAILGUNXM3"),

        GetHashKey("WEAPON_COMBATSHOTGUN"),
        GetHashKey("WEAPON_AUTOSHOTGUN"),
        GetHashKey("WEAPON_PUMPSHOTGUN"),
        GetHashKey("WEAPON_HEAVYSHOTGUN"),
        GetHashKey("WEAPON_PUMPSHOTGUN_MK2"),
        GetHashKey("WEAPON_SAWNOFFSHOTGUN"),
        GetHashKey("WEAPON_BULLPUPSHOTGUN"),
        GetHashKey("WEAPON_ASSAULTSHOTGUN"),
        GetHashKey("WEAPON_DBSHOTGUN"),

        GetHashKey("WEAPON_SNIPERRIFLE"),
        GetHashKey("WEAPON_HEAVYSNIPER_MK2"),
        GetHashKey("WEAPON_HEAVYSNIPER"),
        GetHashKey("WEAPON_MARKSMANRIFLE_MK2"),
        GetHashKey("WEAPON_PRECISIONRIFLE"),
        GetHashKey("WEAPON_MUSKET"),
        GetHashKey("WEAPON_MARKSMANRIFLE"),

        GetHashKey("WEAPON_FIREEXTINGUISHER"), --Feuerlöscher

        GetHashKey("WEAPON_SNOWBALL"),
        GetHashKey("WEAPON_MOLOTOV"),
        GetHashKey("WEAPON_STICKYBOMB"),
        GetHashKey("WEAPON_FLARE"),
        GetHashKey("WEAPON_GRENADE"),
        GetHashKey("WEAPON_BZGAS"),
        GetHashKey("WEAPON_PROXMINE"),
        GetHashKey("WEAPON_PIPEBOMB"),
        GetHashKey("WEAPON_ACIDPACKAGE"),
        GetHashKey("WEAPON_SMOKEGRENADE"),

        GetHashKey("WEAPON_VINTAGEPISTOL"),
        GetHashKey("WEAPON_PISTOL"),
        GetHashKey("WEAPON_PISTOLXM3"),
        GetHashKey("WEAPON_APPISTOL"),
        GetHashKey("WEAPON_CERAMICPISTOL"),
        GetHashKey("WEAPON_FLAREGUN"),
        GetHashKey("WEAPON_GADGETPISTOL"),
        GetHashKey("WEAPON_COMBATPISTOL"),
        GetHashKey("WEAPON_SNSPISTOL_MK2"),
        GetHashKey("WEAPON_NAVYREVOLVER"),
        GetHashKey("WEAPON_DOUBLEACTION"),
        GetHashKey("WEAPON_PISTOL50"),
        GetHashKey("WEAPON_RAYPISTOL"),
        GetHashKey("WEAPON_SNSPISTOL"),
        GetHashKey("WEAPON_PISTOL_MK2"),
        GetHashKey("WEAPON_REVOLVER"),
        GetHashKey("WEAPON_REVOLVER_MK2"),
        GetHashKey("WEAPON_HEAVYPISTOL"),
        GetHashKey("WEAPON_MARKSMANPISTOL"),
    }
}