colors = {}

colors.base = {
    {index = 0, name = 'Black', type = 'metallic', paintType = 1, farbcat = 'black'},
    {index = 1, name = 'Graphite', type = 'metallic', paintType = 1, farbcat = 'black'},
    {index = 2, name = 'Black Steel', type = 'metallic', paintType = 1, farbcat = 'black'},
    {index = 3, name = 'Dark Steel', type = 'metallic', paintType = 1, farbcat = 'black'},
    {index = 4, name = 'Silver', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 5, name = 'Bluish Silver', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 6, name = 'Rolled Steel', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 7, name = 'Shadow Silver', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 8, name = 'Stone Silver', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 9, name = 'Midnight Silver', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 10, name = 'Cast Iron Silver', type = 'metallic', paintType = 1, farbcat = 'silver'},
    {index = 11, name = 'Anhracite Black', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 27, name = 'Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 28, name = 'Torino Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 29, name = 'Formula Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 30, name = 'Blaze Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 31, name = 'Grace Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 32, name = 'Garnet Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 33, name = 'Sunset Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 34, name = 'Cabernet Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 35, name = 'Candy Red', type = 'metallic', paintType = 1, farbcat = 'red'},
    {index = 36, name = 'Sunrise Orange', type = 'metallic', paintType = 1, farbcat = 'orange'},
    {index = 12, name = 'Matt Black', type = 'matte', paintType = 3},
    {index = 13, name = 'Matt Gray', type = 'matte', paintType = 3},
    {index = 14, name = 'Matt Light Gray', type = 'matte', paintType = 3},
    {index = 117, name = 'Brushed Steel', type = 'metals', paintType = 4},
    {index = 117, name = 'Brushed Steel', type = 'metals', paintType = 4},
}
